/*
    CREATE TABLES
*/

CREATE TABLE IF NOT EXISTS client_type
(
    id_client_type BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT client_type_pk PRIMARY KEY,
    client_type    VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS bank_product
(
    id_bank_product  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image            TEXT,
    title            VARCHAR(255)     NOT NULL,
    description      TEXT,
    tariff_price_rub DOUBLE PRECISION NOT NULL,
    id__client_type  BIGINT           NOT NULL
        CONSTRAINT bank_product_id_client_type_fkey REFERENCES client_type
);

COMMENT ON TABLE client_type IS 'Тип клиента';
COMMENT ON TABLE bank_product IS 'Банковские продукты';

/*
    INSERT DATA
*/

INSERT INTO client_type (id_client_type, client_type)
VALUES (1, 'Пенсионер'),
       (2, 'Студент'),
       (3, 'Школьник'),
       (4, 'Семья'),
       (5, 'Военный'),
       (6, 'Предприятие'),
       (7, 'Компания'),
       (8, 'Водитель'),
       (9, 'Геймер');

INSERT INTO bank_product (id_bank_product, title, description, image, tariff_price_rub, id__client_type)
VALUES (1,
        'Дебетовая карта World of Tanks',
        'Карта для настоящих танкистов. Премиум-аккаунт на 30 дней',
        'iuJRoiSZaYEEMBaIbQABPiarSae4UaP3.png',
        100,
        9),
       (2,
        'Дебетовая карта ALL Games',
        'Дебетовая карта геймера. Закажите карту со своим никнеймом, копите бонусы, получайте игры и технику бесплатно',
        'Gyvuw6HhH6zaakRuAwirz6KsYk7oORPu.png',
        2000.2,
        9),
       (3,
        'Дебетовая карта ALL Airlines',
        'Карта для путешествий с любыми авиакомпаниями. Оплачивайте милями 100% цены авиабилета — на любой рейс, направление и дату',
        'wppqsxCceMnR3H6ODva0jILjBMKZqEV7.png',
        0,
        5),
       (4,
        'Дебетовая карта Tinkoff Drive',
        'Дебетовая карта для всех, кто за рулем. Получайте баллы за любые покупки и оплачивайте ими парковку, запчасти, ремонт машины',
        'jDvxCARKL7zZXERe6WCWkgKbex1omxS9.png',
        0,
        8),
       (5,
        'Премиальная карта ALL Airlines Premium',
        'Привычный бизнес-класс. Бесплатные авиабилеты и премиум-страховка для поездок по миру',
        '1R7BSVDM6uYDf5ax94LfP2peI1kysTHp.png',
        5000,
        5),
       (6,
        'Премиальная карта Tinkoff Black Premium',
        'Пользуйтесь картой в 10 странах мира. Получайте привилегии в банке, дома и в поездках',
        'ymJVsGCE1KR1TYQ7oCwdITdIcAZ4BETD.png',
        1990,
        7),
       (7,
        'Детская карта «Тинькофф Джуниор»',
        'Дебетовая карта для детей до 14 лет. Детям — бонусы и приложение с крутым дизайном. Родителям — помощь в воспитании финансово грамотного ребенка',
        'c5SxVFKShnNJmodJKUHp8mGKL8P4Rb7e.png',
        0,
        3),
       (8,
        'Дебетовая карта Физтех-Союза',
        'Для тех, кому небезразличен МФТИ. Получите статус Участника сообщества Физтех-Союза, доход на остаток и кэшбэк за покупки у партнеров',
        'IRm9ML8OERwIG804zffgthUewRklMKep.png',
        800000000000.1,
        2),
       (9,
        'Дебетовая карта ЛУКОЙЛ — Тинькофф',
        'С повышенным кэшбэком на АЗС «ЛУКОЙЛ» — для выгодной заправки',
        'vGyNjWnkXl0QOc9856q4DRrzv2T5RLsW.png',
        0,
        8);