# You may want to run only the PostgreSQL database, not all services at once:
# docker-compose -f docker-compose.database.yml up -d

version: "3"

services:
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

# If you need pgAdmin, uncomment the lines.
# Run service and open localhost:${PGADMIN_DEFAULT_PORT} in your browser.
# To add the database use the name of database service as host: "postgres"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./data/pgadmin_data:/var/lib/pgadmin
#    ports:
#      - "${PGADMIN_DEFAULT_PORT}:80"
#    restart: unless-stopped
