version: "2.4"

services:
  database:
    extends:
      file: docker-compose.database.yml
      service: database

  server:
    extends:
      file: docker-compose.prod.yml
      service: server
    ports:
      - ${LOCAL_SERVER_PORT}:80
    volumes:
      - ./server:/app
