version: "2.4"

services:
  database:
    extends:
      file: docker-compose.database.yml
      service: database

  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./data/server_files:/app/files
    ports:
      - ${LOCAL_SERVER_PORT}:80
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  client:
    container_name: spo-client-prod
    build:
      context: client
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    ports:
      - ${LOCAL_CLIENT_PORT}:80
    environment:
      REACT_APP_SERVER_HOST: server
      REACT_APP_SERVER_PORT: 80
